Models/Brand.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitalX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Brand
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand()
        {
            this.Products = new HashSet<Product>();
        }
    
        public short BrandID { get; set; }
        
        [Required(ErrorMessage = "Enter Brand Name")]
        [StringLength(50, ErrorMessage = "{0} should have maximum {1} characters")]
        public string Name { get; set; }

        public long UpdatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}

Controllers/BrandController.cs
using DigitalX.Models;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System;
using System.Collections.Generic;
using System.Reflection;
using System.ComponentModel.DataAnnotations.Schema;

namespace DigitalX.Controllers
{
    [CustomAuthenticationFilter]
    [AuthorizeRoles("Admin", "Product")]
    public class BrandController : Controller
    {     
        private DigitalXDBEntities db = new DigitalXDBEntities();

        public ActionResult List()
        {
            return View(db.Brands.ToList());
        }


        public ActionResult _Edit(int id)
        {     
            return PartialView(db.Brands.Find(id));
        }

        [HttpPost]
        public ActionResult _Edit(Brand editedBrand)
        {      
            if (ModelState.IsValid)
            {
                Brand item = db.Brands.Find(editedBrand.BrandID);
               
                item.Name = editedBrand.Name;
                item.UpdatedBy = ((Employee)Session["CurrentUser"]).EmpID;

                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                ModelState.Clear();

                TempData["alertMsg"] = "Brand is updated successfully ";
                TempData["alertClass"] = "alert-success";
                return View("List", db.Brands.ToList());
            }
            else
            {
                return PartialView(editedBrand.BrandID);
            }
        }

      
        public ActionResult Delete(int id)
        {
            //Check if no products linked to this brand
            int productCount = db.Products.Count(x => x.BrandID == id);

            if (productCount>0)
            {
                TempData["alertMsg"] = "The brand cannot be deleted unless it has associated products";
                TempData["alertClass"] = "alert-warning";          
            }
            else
            {
                var brandItem = db.Brands.Find(id);
                db.Brands.Remove(brandItem);
                db.SaveChanges();
                TempData["alertMsg"] = "\"" + brandItem.Name + "\" is deleted successfully";
                TempData["alertClass"] = "alert-success";
            }
            var updatedBrands = db.Brands.ToList();
            return View("List", updatedBrands);
        }

        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            if (ModelState.IsValid)
            {
                if (!string.IsNullOrEmpty(form["brandName"]))
                    {
                    Brand item = new Brand();
                    item.Name = form["brandName"].ToString();
                    item.UpdatedBy = ((Employee)Session["CurrentUser"]).EmpID;
                    db.Brands.Add(item);
                    ModelState.Clear();
                    db.SaveChanges();

                    TempData["alertMsg"]  = "New Brand is added successfully";
                    TempData["alertClass"] = "alert-success";
                }
            }
            else
            {
                TempData["alertMsg"] = "Invalid Data State";
                TempData["alertClass"] = "alert-danger";
            }
            return View("List", db.Brands.ToList());
        }

        public ActionResult _BrandList()
        {
            return PartialView(db.Brands.ToList());
        }

        [HttpPost]
        public ActionResult _BrandList(FormCollection form)
        {
            TempData["selectedBrandID"]= form["ddlBrand"].ToString();
            return PartialView(db.Brands.ToList());
        }
    }
}

Views/Brand/Index.cshtml
@model IEnumerable<DigitalX.Models.Brand>

@{
    ViewBag.Title = "Brands ";
}


    <div>       
        <div>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Add New Brand Here!</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.Hidden("UpdatedBy", Session["loggedInUserID"])
                        @Html.Label("Brand Name", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.Editor("brandName", new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessage("brandName", "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
              }
        </div>
        <h3>List of All Brands</h3> <h4>@ViewBag.msg</h4>
        <hr />
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        Brand ID
                    </th>
                    <th>
                        Brand Name
                    </th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            @foreach (var x in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(model => x.BrandID)
                    </td>
                    <td>
                        @Html.DisplayFor(model => x.Name)
                    </td>
                    <td>

                        <a href="@Html.Partial("Edit", new { id = x.BrandID})">Edit</a>
                    </td>
                    <td>
                        <button type="button" class="btn btn-primary" data-id="x.BrandID" data-toggle="modal" data-target="#myModal" />
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = x.BrandID }, new
                        {
                         onclick = "return confirm('Do you really want to delete this Brand?')"
                        })
                    </td>
                </tr>
            }
        </table>
    </div>

Views/Brand/List.cshtml
@model IEnumerable<DigitalX.Models.Brand>

@{
    ViewBag.Title = "Brands";
}
@Html.Action("_AlertBox", "Home")
    <div class="container-fluid">
        <div class="row top-short-form">
            @using (Html.BeginForm("Create", "Brand", FormMethod.Post))
            {
             @Html.AntiForgeryToken()
                <div class="form-horizontal form-inline">
                    <h4 class="heading-lighter">Add New Brand Here!</h4>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        <div class="col-md-5">
                            @Html.Editor("brandName", new { htmlAttributes = new { @class = "form-control", @required = "required",@maxLength="50", @placeholder="Brand Name"} })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
             }
        </div>
        <div class="row">
            <div class="my-panel">
                <h4 class="heading-lighter heading-centered">List of Brands</h4>
                <table class="table table-hover" style="width:99%;">
                    <thead class="thead-dark">
                        <tr>
                            <th>Brand ID</th>
                            <th>
                                Name
                            </th>
                            <th></th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var x in Model)
                        {
                            <tr>
                                <td class="col-md-2">
                                    @x.BrandID
                                </td>
                                <td class="col-md-3">
                                    @x.Name
                                </td>
                                <td class="col-md-2">
                                    <a data-toggle="modal" href="@Url.Action("_Edit","Brand",new {id = x.BrandID})" data-target="#@(x.BrandID + "_modal")">Edit</a>

                                    <!-- Modal -->
                                    <div class="modal fade" id="@(x.BrandID + "_modal")" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                            </div>
                                        </div>
                                    </div>                      |
                                    @Html.ActionLink("Delete", "Delete", new { id = x.BrandID }, new
                                    {
                                    onclick = "return confirm('Are you sure, you want to delete this Brand?')"
                                    })
                                </td>
                                <td class="col-md-5">
                                    <div class="panel panel-default" style="width:400px;margin-bottom:0px;">
                                        <div class="panel-heading heading-centered">
                                            <a data-toggle="collapse" href="#@x.BrandID">View Products</a>
                                        </div>
                                        <div id="@x.BrandID" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <table class="table-condensed table-striped space-saver" style="width:98%;">
                                                    @foreach (DigitalX.Models.Product p in x.Products.Where(p => p.IsActive == true))
                                                    {
                                                        <tr>
                                                            <td>
                                                                <img class="product-thumbnail" src="@(String.Format("{0}/{1}", System.Web.Configuration.WebConfigurationManager.AppSettings["ProductImagePath"].ToString(), p.Picture))" />
                                                            </td>
                                                            <td>
                                                                @Html.ActionLink(p.Name , "Detail", "Product", new { id = p.ProductID }, null)
                                                            </td>
                                                            <td>
                                                                @Html.ActionLink("Edit", "Edit", "Product", new { id = p.ProductID }, null)
                                                            </td>
                                                        </tr>
                                                    }
                                                </table>
                                            </div>
                                            <div class="panel-footer">Total:  @x.Products.Where(p => p.IsActive == true).Count()</div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

Views/Brand/_Edit.cshtml
@model DigitalX.Models.Brand

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title heading-lighter" id="exampleModalLabel">Edit brand name here!</h4>
</div>
@using (Html.BeginForm("_Edit","Brand",FormMethod.Post))
{
    <div class="modal-body">
        @Html.HiddenFor(model =>model.BrandID,Model.BrandID)
        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control",@required="required",@placeholder=Model.Name, @maxLength="50"} })
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-colored" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-colored">Update</button>
    </div>
}